name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cargo-vcpkg
      run: cargo install cargo-vcpkg
    - name: install deps
      run: cargo vcpkg -v build
    - name: Build
      run: cargo build --verbose -r
    - uses: fnkr/github-action-ghr@v1
      env:
            GHR_COMPRESS: xz
            GHR_PATH: target/release/
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
